platform:ios,'7.0'
target :MLProject do
pod 'Mantle'
pod 'ReactiveCocoa'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'AFNetworking'
pod 'UITableView+FDTemplateLayoutCell', "~> 1.3"
pod 'MMDrawerController'
pod 'IQKeyboardManager'
pod 'YYKit'
pod 'FMDB'
pod 'DZNEmptyDataSet'
pod 'Realm'
pod 'Reachability'
pod 'CSStickyHeaderFlowLayout'
pod 'Aspects'
pod 'BlocksKit'
pod 'PromiseKit'
pod 'MLeaksFinder'
pod 'SDWebImage'
pod 'FLAnimatedImage'
end
