platform:ios,'7.0'
pod 'Mantle'
pod 'ReactiveCocoa'
pod 'MJExtension'
pod 'Masonry'
pod 'AFNetworking'
pod 'UITableView+FDTemplateLayoutCell', "~> 1.3"
pod 'MMDrawerController'
pod 'IQKeyboardManager'
pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'
pod 'YYKit'
pod 'AsyncDisplayKit'
pod 'FMDB'